Vald:
  db_label: vald-local
  task_label: vald-smoke
  case_type: Performance768D10K
  host: localhost
  port: 8081
  use_tls: false
  batch_size: 64
  metric_type: COSINE
  num: 10
  wait_for_sync_seconds: 5
